### ISSUE TITLE
关于 my-snippet

### ISSUE THREAD

**Issue by LauGaHo** [gin-18/nvim#1]
想请问一下，那个 my-snippet 是如何使用的？是否需要在哪个文件进行导入？

**Comment by gin-18** [comment]
可以在 `my-snippet/snippets` 目录中添加对应语言的代码片段 `<filetype>.json`。
添加完成后在 `my-snippet/package.json` 文件中的 `snippets` 属性中引入刚刚添加的代码片段：
```json
"snippets": [
    {
        "language": [
        "<filetype>"
        ],
        "path": "./snippets/<filetype>.json"
    }
 ]
```

**Comment by LauGaHo** [comment]
我按照你的文件进行了配置之后，在 nvim 编辑器中输入了 `,h1` 之后，显示的时候 `,` 还会在文档中，就变成了 `,#Title` 这样，不知道是不是有什么地方忽略掉了吗？

**Comment by gin-18** [comment]
可以提供一下关于 `snippet` 的相关配置吗？这样可能会直观一些。

**Comment by LauGaHo** [comment]
![package.json](https://cdn.jsdelivr.net/gh/LauGaHo/blog-img@master/uPic/eKBGuP.png)
![markdown.json](https://cdn.jsdelivr.net/gh/LauGaHo/blog-img@master/uPic/PMwiLJ.png)
![nvim-cmp](https://cdn.jsdelivr.net/gh/LauGaHo/blog-img@master/uPic/ETTBGI.png)

使用效果如下：

![effect1](https://cdn.jsdelivr.net/gh/LauGaHo/blog-img@master/uPic/asNfob.png)
![effect2](https://cdn.jsdelivr.net/gh/LauGaHo/blog-img@master/uPic/Lvkd5h.png)

如上图片所示，会有一个 `,`。

**Comment by gin-18** [comment]
不好意思，配置已经有所修改，直接输入 `h1` 就可以了，不需要再输入 `,` 了。
在 `<filetype>.json` 文件中的 `prefix` 属性配置的就是触发补全所输入的内容。
```json
{
  "h1 title": {
      "prefix": "h1", 这里填的是什么，就输入什么就可以了
   }
}
```
另外，关于这个配置的所有说明都会及时地更新在 `README` 中，看 `README` 可能是一个更好的选择。

**Comment by LauGaHo** [comment]
好的，我看到了，可能我没有看到 `README.md` 中最新的内容，抱歉，问题已经解决了，谢谢。我顺手 `star` 一个。
